{{- if .Values.backup.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: halyard
    role: cron
  name: halyard-cron
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 11 * * *"
  jobTemplate:
    metadata:
      labels:
        app: halyard
        role: cron
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: halyard-cron
            image: {{ .Values.image }}
            command: [ "/backup.sh" ]
            env:
            - name: AWS_BUCKET
              value: {{ .Values.backup.awsBucket }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.awsSecret }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.awsSecret }}
                  key: aws_secret_access_key
            terminationMessagePolicy: FallbackToLogsOnError
            volumeMounts:
            - name: root-volume
              mountPath: /root
          volumes:
          - name: root-volume
            persistentVolumeClaim:
              claimName: halyard
{{- end }}
